# LLM Evaluation for Detection of Toxic Alcohol and Methanol Poisoning Events

Dataset and evaluation code for benchmarking a large language model for detecting toxic alcohol and methanol poisoning events from open-source intelligence (OSINT) news articles.

This repository contains the evaluation dataset and evaluation code used to assess the performance of a large language model (LLM) for detecting toxic alcohol and methanol poisoning events from news articles.

The repository accompanies the manuscript:

**Toxic Alcohol and Methanol Poisoning Threat Detection Using a Large Language Model**

The aim of this repository is to enable reproducibility of the evaluation framework and provide a benchmark dataset for future research in event-based public health surveillance of toxic alcohol exposures using large language models.

## Overview

Toxic alcohol and methanol poisonings remain a persistent global public health threat, causing severe morbidity, permanent blindness, and high mortality. Traditional surveillance for these events relies on individual country programs that are inconsistent in coverage and subject to substantial reporting delays, leaving persistent gaps in global situational awareness.

Large language models are increasingly used for automated detection of emerging public health threats from open-source intelligence (OSINT) such as news media. However, reproducible evaluation frameworks for assessing their ability to extract structured event information from such sources remain limited, particularly in the toxic alcohol and methanol poisoning domain.

This repository provides:

- A gold-standard annotated dataset of 100 news articles
- Human annotation outputs (one file)
- LLM extraction outputs (same file as above)
- The evaluation pipeline used to compute precision, recall, and F1 scores

The repository allows independent researchers to reproduce the evaluation results reported in the manuscript.

## Dataset

The evaluation dataset contains 100 news articles manually annotated by two domain-trained reviewers, drawn from a six-month OSINT corpus (30 August 2024 – 31 January 2025) collected via the Bing News API using 17 search terms related to methanol poisoning and adulterated or toxic alcohol events.

Each row represents a single article.

Columns include:

| Column | Description |
|--------|-------------|
| `_id` | Unique article identifier |
| `url` | Source article URL |
| `gpt4o` | Structured extraction generated by the LLM (GPT-4o, zero-shot) |
| `feedback` | Human gold-standard annotation |

Annotations follow a structured bullet-list format representing entities extracted from each article.

## Entity Types Evaluated

The evaluation measures extraction performance for the following entities:

- Event identification (toxic alcohol detection / methanol poisoning event)
- FATALITY COUNT
- CASE NUMBER (hospitalised and non-hospitalised)
- LOCATION
  - Country
  - Subnational region (state/province)
  - County
  - City
- DATE (specific calendar date or day of the week explicitly associated with the event)
- TEMPORAL EXPRESSIONS
  - Years
  - Months
  - Relative time phrases
  - Adverbs of time

Two reporting transformations are applied in the evaluation script:

- `LOCATION` → standardised hierarchy (Country / State / County / City)
- `Answer` → `Event identification`

These transformations do not alter the underlying annotations but standardise reporting terminology.

## Evaluation Method

The evaluation script computes entity-level performance metrics:

- Precision
- Recall
- F1 score
- 95% Clopper–Pearson confidence intervals
- Inter-annotator agreement (Cohen's κ and per cent agreement)

The script performs:

- Parsing of structured entity annotations
- Label normalisation
- Entity matching using:
  - exact matching
  - semantic similarity using sentence embeddings
- Calculation of evaluation metrics at the document level (consistent with surveillance-oriented NER benchmarks)

Embedding-based matching uses: `sentence-transformers/all-MiniLM-L6-v2`

The LLM evaluated is **GPT-4o**, run in zero-shot mode with deterministic inference (`temperature = 0.0`, `top_p = 0.1`) and a 3,000-token response cap. No fine-tuning or few-shot exemplars were used.

## Installation

Clone the repository:

```bash
git clone https://github.com/YOUR_USERNAME/llm-methanol-event-detection-evaluation.git
cd llm-methanol-event-detection-evaluation
```

Install dependencies:

```bash
pip install -r requirements.txt
```

## Running the Evaluation

Run the evaluation script:

```bash
python scripts/ner_evaluation.py \
  --input data/evaluation_dataset_100_articles.xlsx \
  --output results/evaluation_results.csv
```

The script will generate `evaluation_results.csv` containing the entity-level evaluation metrics.

## Reproducibility

The proprietary components used to collect and process the original news data (including Bing News API ingestion pipelines and large-scale scraping infrastructure) are not included in this repository due to institutional and contractual restrictions.

However, the following reproducible components are provided:

- the LLM inference outputs
- the human gold-standard annotations
- the evaluation code

These resources allow independent researchers to reproduce the evaluation results.

## License

This repository is released under the MIT License.

## Citation

If you use this dataset or evaluation framework, please cite:

*(To be added once published)*
